### ISSUE TITLE
git geo setup replaces post-commit hook

### ISSUE THREAD

**Issue by Bjoern** [peritus/geocommit#8]
I had something else in post-commit and it was gone after executing git geo setup. I think git geo setup should append to the file, not replace it.

**Comment by naderman** [comment]
It does keep your old post commit file around however, now called post-commit-partial and executes that file before it runs geocommit code. I'd say keeping the old post-commit in a separate file is more convenient, since there is absolutely no guarantee for what language the existing post-commit code is written in. So we can hardly edit it correctly.
